server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:

        - id: member-update-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/update
          filters:
            - JwtFilter
        - id: member-update-by-admin-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/update/admin
          filters:
            - JwtFilter
            - AdminFilter
        - id: member-delete-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member
            - Method=DELETE
          filters:
            - JwtFilter
        - id: member-search-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/{page_num}
            - Method=GET
          filters:
            - JwtFilter
            - AdminFilter
        - id: org-waiting-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/waiting-list/{page_num}
          filters:
            - JwtFilter
            - AdminFilter
        - id: org-waiting-detail-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/waiting-detail/{member_id}
          filters:
            - JwtFilter
            - AdminFilter
        - id: org-permition-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/permission
          filters:
            - JwtFilter
            - AdminFilter
        - id: admin-list-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/search/{type}/{content}/{page_num}
          filters:
            - JwtFilter
            - AdminFilter
        - id: admin-warning-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/warning
          filters:
            - JwtFilter
            - AdminFilter
        - id: desk-search-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/desk/member/{page_num}
          filters:
            - JwtFilter
        - id: desk-write-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/desk
            - Method=POST,PUT
          filters:
            - JwtFilter
        - id: desk-detail-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/desk/{help_desk_id}
          filters:
            - JwtFilter
        - id: desk-comment-write-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/desk/comment
            - Method=POST
          filters:
            - JwtFilter
            - AdminFilter
        - id: desk-comment-delete-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/desk/comment
            - Method=DELETE
          filters:
            - JwtFilter
        - id: certi-search-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/certi/check
          filters:
            - JwtFilter
        - id: certi-write-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/certi
          filters:
            - JwtFilter
        - id: member-services
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
        - id: volunteer-service
          uri: lb://VOLUNTEER-SERVICE
          predicates:
            - Path=/vol/**